chapter8-mail/src/main/java/me/kafeitu/activiti/chapter7/entity/Leave.java
package me.kafeitu.activiti.chapter7.entity;

import org.activiti.engine.repository.ProcessDefinition;
import org.activiti.engine.runtime.ProcessInstance;
import org.activiti.engine.task.Task;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;

/**
 * Entity: Leave
 *
 * @author HenryYan
 */
@Entity
@Table(name = "LEAVE")
public class Leave implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String processInstanceId;
    private String userId;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date startTime;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date endTime;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date realityStartTime;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date realityEndTime;

    private Date applyTime;
    private String leaveType;
    private String reason;

    // 流程任务
    private Task task;

    private Map<String, Object> variables;

    // 运行中的流程实例
    private ProcessInstance processInstance;

    // 流程定义
    private ProcessDefinition processDefinition;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    @Column
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME")
    public Date getStartTime() {
        return startTime;
    }

    @Transient
    public String getStringStartDate() {
        if (startTime == null) {
            return "";
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(startTime);
    }

    @Transient
    public String getStringStartTime() {
        if (startTime == null) {
            return "";
        }
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        return sdf.format(startTime);
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END_TIME")
    public Date getEndTime() {
        return endTime;
    }

    @Transient
    public String getStringEndDate() {
        if (endTime == null) {
            return "";
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(endTime);
    }

    @Transient
    public String getStringEndTime() {
        if (endTime == null) {
            return "";
        }
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        return sdf.format(endTime);
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Column
    @Temporal(TemporalType.TIMESTAMP)
    public Date getApplyTime() {
        return applyTime;
    }

    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    @Column
    public String getLeaveType() {
        return leaveType;
    }

    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }

    @Column
    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "REALITY_START_TIME")
    public Date getRealityStartTime() {
        return realityStartTime;
    }

    public void setRealityStartTime(Date realityStartTime) {
        this.realityStartTime = realityStartTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "REALITY_END_TIME")
    public Date getRealityEndTime() {
        return realityEndTime;
    }

    public void setRealityEndTime(Date realityEndTime) {
        this.realityEndTime = realityEndTime;
    }

    @Transient
    public Task getTask() {
        return task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    @Transient
    public Map<String, Object> getVariables() {
        return variables;
    }

    public void setVariables(Map<String, Object> variables) {
        this.variables = variables;
    }

    @Transient
    public ProcessInstance getProcessInstance() {
        return processInstance;
    }

    public void setProcessInstance(ProcessInstance processInstance) {
        this.processInstance = processInstance;
    }

    @Transient
    public ProcessDefinition getProcessDefinition() {
        return processDefinition;
    }

    public void setProcessDefinition(ProcessDefinition processDefinition) {
        this.processDefinition = processDefinition;
    }

}

chapter8-mail/src/main/java/me/kafeitu/activiti/web/chapter7/LeaveController.java
package me.kafeitu.activiti.web.chapter7;

import me.kafeitu.activiti.chapter6.util.UserUtil;
import me.kafeitu.activiti.chapter7.entity.Leave;
import me.kafeitu.activiti.chapter7.service.LeaveManager;
import me.kafeitu.activiti.chapter7.service.LeaveWorkflowService;
import org.activiti.engine.ActivitiException;
import org.activiti.engine.RuntimeService;
import org.activiti.engine.TaskService;
import org.activiti.engine.identity.User;
import org.activiti.engine.runtime.ProcessInstance;
import org.activiti.engine.task.Task;
import org.apache.commons.lang3.BooleanUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 请假控制器
 *
 * @author henryyan
 */
@Controller
@RequestMapping(value = "/chapter7/leave")
public class LeaveController {

    private Logger logger = LoggerFactory.getLogger(getClass());

    @Autowired
    private LeaveManager leaveManager;

    @Autowired
    private LeaveWorkflowService leaveService;

    @Autowired
    private TaskService taskService;

    @Autowired
    private RuntimeService runtimeService;

    @RequestMapping(value = {"apply", ""})
    public String createForm(Model model) {
        model.addAttribute("leave", new Leave());
        return "/chapter7/leave/leave-apply";
    }

    /**
     * 启动请假流程
     */
    @RequestMapping(value = "start", method = RequestMethod.POST)
    public String startWorkflow(Leave leave, RedirectAttributes redirectAttributes, HttpSession session) {
        try {
            User user = UserUtil.getUserFromSession(session);
            Map<String, Object> variables = new HashMap<String, Object>();
            ProcessInstance processInstance = leaveService.startWorkflow(leave, user.getId(), variables);
            redirectAttributes.addFlashAttribute("message", "流程已启动，流程ID：" + processInstance.getId());
        } catch (ActivitiException e) {
            if (e.getMessage().indexOf("no processes deployed with key") != -1) {
                logger.warn("没有部署流程!", e);
                redirectAttributes.addFlashAttribute("error", "没有部署请假流程");
            } else {
                logger.error("启动请假流程失败：", e);
                redirectAttributes.addFlashAttribute("error", "系统内部错误！");
            }
        } catch (Exception e) {
            logger.error("启动请假流程失败：", e);
            redirectAttributes.addFlashAttribute("error", "系统内部错误！");
        }
        return "redirect:/chapter7/leave/apply";
    }

    /**
     * 任务列表
     *
     * @param leave
     */
    @RequestMapping(value = "task/list")
    public ModelAndView taskList(HttpSession session) {
        ModelAndView mav = new ModelAndView("/chapter7/leave/leave-task-list");
        String userId = UserUtil.getUserFromSession(session).getId();
        List<Leave> results = leaveService.findTodoTasks(userId);
        mav.addObject("records", results);
        return mav;
    }

    /**
     * 签收任务
     */
    @RequestMapping(value = "task/claim/{id}")
    public String claim(@PathVariable("id") String taskId, HttpSession session, RedirectAttributes redirectAttributes) {
        String userId = UserUtil.getUserFromSession(session).getId();
        taskService.claim(taskId, userId);
        redirectAttributes.addFlashAttribute("message", "任务已签收");
        return "redirect:/chapter7/leave/task/list";
    }

    /**
     * 任务列表
     *
     * @param leave
     */
    @RequestMapping(value = "task/view/{taskId}")
    public ModelAndView showTaskView(@PathVariable("taskId") String taskId) {
        Task task = taskService.createTaskQuery().taskId(taskId).singleResult();
        String processInstanceId = task.getProcessInstanceId();
        ProcessInstance processInstance = runtimeService.createProcessInstanceQuery().processInstanceId(processInstanceId).singleResult();
        Leave leave = leaveManager.get(new Long(processInstance.getBusinessKey()));
        ModelAndView mav = new ModelAndView("/chapter7/leave/task-" + task.getTaskDefinitionKey());
        mav.addObject("leave", leave);
        mav.addObject("task", task);
        return mav;
    }

    /**
     * 完成任务
     *
     * @param id
     * @return
     */
    @RequestMapping(value = "task/complete/{id}", method = {RequestMethod.POST, RequestMethod.GET})
    @SuppressWarnings("unchecked")
    public String complete(@PathVariable("id") String taskId, @RequestParam(value = "saveEntity", required = false) String saveEntity,
                           @ModelAttribute("preloadLeave") Leave leave, HttpServletRequest request, RedirectAttributes redirectAttributes) {
        boolean saveEntityBoolean = BooleanUtils.toBoolean(saveEntity);
        Map<String, Object> variables = new HashMap<String, Object>();
        Enumeration<String> parameterNames = request.getParameterNames();
        try {
            while (parameterNames.hasMoreElements()) {
                String parameterName = (String) parameterNames.nextElement();
                if (parameterName.startsWith("p_")) {
                    // 参数结构：p_B_name，p为参数的前缀，B为类型，name为属性名称
                    String[] parameter = parameterName.split("_");
                    if (parameter.length == 3) {
                        String paramValue = request.getParameter(parameterName);
                        Object value = paramValue;
                        if (parameter[1].equals("B")) {
                            value = BooleanUtils.toBoolean(paramValue);
                        } else if (parameter[1].equals("DT")) {
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
                            value = sdf.parse(paramValue);
                        }
                        variables.put(parameter[2], value);
                    } else {
                        throw new RuntimeException("invalid parameter for activiti variable: " + parameterName);
                    }
                }
            }
            leaveService.complete(leave, saveEntityBoolean, taskId, variables);
            redirectAttributes.addFlashAttribute("message", "任务已完成");
        } catch (Exception e) {
            logger.error("error on complete task {}, variables={}", new Object[]{taskId, variables, e});
            request.setAttribute("error", "完成任务失败");
        }
        return "redirect:/chapter7/leave/task/list";
    }

    /**
     * 自动绑定页面字段
     */
    @ModelAttribute("preloadLeave")
    public Leave getLeave(@RequestParam(value = "id", required = false) Long id, HttpSession session) {
        if (id != null) {
            return leaveManager.get(id);
        }
        return new Leave();
    }

}

chapter8-mail/src/main/webapp/WEB-INF/views/chapter7/leave/leave-apply.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
	<link rel="stylesheet" href="${ctx}/js/common/plugins/timepicker.css">
	<title>请假申请</title>
	<script type="text/javascript" src="${ctx }/js/common/jquery.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap.min.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap-datepicker.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/plugins/bootstrap-timepicker.js"></script>
	<script type="text/javascript">
	$(function() {
		$('.datepicker').datepicker();
		$('.time').timepicker({
			minuteStep: 10,
            showMeridian: false
		});
	});

	function beforeSend() {
		$('input[name=startTime]').val($('#startDate').val() + ' ' + $('#startTime').val());
		$('input[name=endTime]').val($('#endDate').val() + ' ' + $('#endTime').val());
	}
	</script>
</head>
<body>
	<c:if test="${not empty message}">
		<div id="message" class="alert alert-success">${message}</div>
		<!-- 自动隐藏提示信息 -->
		<script type="text/javascript">
		setTimeout(function() {
			$('#message').hide('slow');
		}, 5000);
		</script>
	</c:if>
	<form action="${ctx }/chapter7/leave/start" class="form-horizontal" method="post" onsubmit="beforeSend()">
		<input type="hidden" name="startTime" />
		<input type="hidden" name="endTime" />
		<fieldset>
			<legend><small>请假申请</small></legend>
			<div id="messageBox" class="alert alert-error input-large controls" style="display:none">输入有误，请先更正。</div>
			<div class="control-group">
				<label for="loginName" class="control-label">请假类型:</label>
				<div class="controls">
					<select id="leaveType" name="leaveType" class="required">
						<option>公休</option>
						<option>病假</option>
						<option>调休</option>
						<option>事假</option>
						<option>婚假</option>
					</select>
				</div>
			</div>
			<div class="control-group">
				<label for="name" class="control-label">开始时间:</label>
				<div class="controls">
					<input type="text" id="startDate" class="datepicker input-small" data-date-format="yyyy-mm-dd" />
					<input type="text" id="startTime" class="time input-small" />
				</div>
			</div>
			<div class="control-group">
				<label for="plainPassword" class="control-label">结束时间:</label>
				<div class="controls">
					<input type="text" id="endDate" class="datepicker input-small" data-date-format="yyyy-mm-dd" />
					<input type="text" id="endTime" class="time input-small" />
				</div>
			</div>
			<div class="control-group">
				<label for="groupList" class="control-label">请假原因:</label>
				<div class="controls">
					<textarea name="reason"></textarea>
				</div>
			</div>
			<div class="form-actions">
				<button type="submit" class="btn"><i class="icon-play"></i>启动流程</button>
			</div>
		</fieldset>
	</form>
</body>
</html>

chapter8-mail/src/main/webapp/WEB-INF/views/chapter7/leave/leave-task-list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
	<title>请假流程待办任务列表--chapter7</title>

	<script src="${ctx }/js/common/jquery.js" type="text/javascript"></script>
</head>
<body>
	<c:if test="${not empty message}">
		<div id="message" class="alert alert-success">${message}</div>
		<!-- 自动隐藏提示信息 -->
		<script type="text/javascript">
		setTimeout(function() {
			$('#message').hide('slow');
		}, 5000);
		</script>
	</c:if>
	<table width="100%" class="table table-bordered table-hover table-condensed" style="margin-top: 5em;">
		<thead>
			<tr>
				<th>申请人</th>
				<th>类型</th>
				<th>请假时间</th>
				<th>请假原因</th>
				<th>任务ID</th>
				<th>任务名称</th>
				<th>流程实例ID</th>
				<th>流程定义ID</th>
				<th>任务创建时间</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${records }" var="leave">
				<tr>
					<td>${leave.userId}</td>
					<td>${leave.leaveType}</td>
					<td>${leave.startTime}至<br/>${leave.endTime}</td>
					<td>${leave.reason}</td>
					<td>${leave.task.id }</td>
					<td>${leave.task.name }</td>
					<td>${leave.task.processInstanceId }</td>
					<td>${leave.task.processDefinitionId }</td>
					<td>${leave.task.createTime }</td>
					<td>
						<c:if test="${empty leave.task.assignee }">
							<a class="btn" href="claim/${leave.task.id}"><i class="icon-eye-open"></i>签收</a>
						</c:if>
						<c:if test="${not empty leave.task.assignee }">
							<a class="btn" href="view/${leave.task.id}"><i class="icon-user"></i>办理</a>
						</c:if>
					</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>
</body>
</html>

chapter8-mail/src/main/webapp/WEB-INF/views/chapter7/leave/task-deptLeaderVerify.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
</head>
<body>
	<form action="${ctx }/chapter7/leave/task/complete/${task.id}" class="form-horizontal" method="post">
		<input type="hidden" name="id" value="${leave.id}" />
		<fieldset>
			<legend><small>${task.name}</small></legend>
			<div class="control-group">
				<label for="loginName" class="control-label">申请人:</label>
				<div class="controls">${leave.userId}</div>
			</div>
			<div class="control-group">
				<label for="loginName" class="control-label">申请时间:</label>
				<div class="controls">${leave.applyTime}</div>
			</div>
			<div class="control-group">
				<label for="loginName" class="control-label">请假类型:</label>
				<div class="controls">${leave.leaveType}</div>
			</div>
			<div class="control-group">
				<label for="name" class="control-label">开始时间:</label>
				<div class="controls">${leave.startTime}</div>
			</div>
			<div class="control-group">
				<label for="plainPassword" class="control-label">结束时间:</label>
				<div class="controls">${leave.endTime}</div>
			</div>
			<div class="control-group">
				<label for="groupList" class="control-label">请假原因:</label>
				<div class="controls">${leave.reason}</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="deptLeaderApproved">审批意见：</label>
				<div class="controls">
					<select name="p_B_deptLeaderApproved" id="deptLeaderApproved">
						<option value="true">同意</option>
						<option value="false">拒绝</option>
					</select>
				</div>
			</div>
			<div class="form-actions">
				<button type="submit" class="btn"><i class="icon-ok"></i>完成任务</button>
			</div>
		</fieldset>
	</form>
</body>
</html>

chapter8-mail/src/main/webapp/WEB-INF/views/chapter7/leave/task-hrVerify.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
	<link rel="stylesheet" href="${ctx}/js/common/plugins/timepicker.css">
	<title>请假--${task.name}</title>
</head>
<body>
	<form action="${ctx }/chapter7/leave/task/complete/${task.id}" class="form-horizontal" method="post" onsubmit="beforeSend()">
		<input type="hidden" name="id" value="${leave.id}" />
		<fieldset>
			<legend><small>${task.name}</small></legend>
			<div class="control-group">
				<label for="loginName" class="control-label">申请人:</label>
				<div class="controls">${leave.userId}</div>
			</div>
			<div class="control-group">
				<label for="loginName" class="control-label">申请时间:</label>
				<div class="controls">${leave.applyTime}</div>
			</div>
			<div class="control-group">
				<label for="loginName" class="control-label">请假类型:</label>
				<div class="controls">${leave.leaveType}</div>
			</div>
			<div class="control-group">
				<label for="name" class="control-label">开始时间:</label>
				<div class="controls">${leave.startTime}</div>
			</div>
			<div class="control-group">
				<label for="plainPassword" class="control-label">结束时间:</label>
				<div class="controls">${leave.endTime}</div>
			</div>
			<div class="control-group">
				<label for="groupList" class="control-label">请假原因:</label>
				<div class="controls">${leave.reason}</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="hrApproved">是否继续申请：</label>
				<div class="controls">
					<select id="hrApproved" name="p_B_hrApproved">
						<option value="true">同意</option>
						<option value="false">拒绝</option>
					</select>
				</div>
			</div>
			<div class="form-actions">
				<button type="submit" class="btn"><i class="icon-ok"></i>完成任务</button>
			</div>
		</fieldset>
	</form>
</body>
</html>

chapter8-mail/src/main/webapp/WEB-INF/views/chapter7/leave/task-modifyApply.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
	<link rel="stylesheet" href="${ctx}/js/common/plugins/timepicker.css">
	<title>请假申请--${task.name}</title>
	<script type="text/javascript" src="${ctx }/js/common/jquery.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap.min.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap-datepicker.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/plugins/bootstrap-timepicker.js"></script>
	<script type="text/javascript">
	$(function() {
		$('.datepicker').datepicker();
		$('.time').timepicker({
			minuteStep: 10,
            showMeridian: false
		});
	});

	function beforeSend() {
		$('input[name=startTime]').val($('#startDate').val() + ' ' + $('#startTime').val());
		$('input[name=endTime]').val($('#endDate').val() + ' ' + $('#endTime').val());
	}
	</script>
</head>
<body>
	<form action="${ctx }/chapter7/leave/task/complete/${task.id}" class="form-horizontal" method="post" onsubmit="beforeSend()">
		<input type="hidden" name="id" value="${leave.id}" />
		<input type="hidden" name="startTime" />
		<input type="hidden" name="endTime" />
		<input type="hidden" name="saveEntity" value="true" />
		<fieldset>
			<legend><small>${task.name}</small></legend>
			<div class="control-group">
				<label for="loginName" class="control-label">请假类型:</label>
				<div class="controls">
					<select id="leaveType" name="leaveType" class="required">
						<option>公休</option>
						<option>病假</option>
						<option>调休</option>
						<option>事假</option>
						<option>婚假</option>
					</select>
				</div>
			</div>
			<div class="control-group">
				<label for="name" class="control-label">开始时间:</label>
				<div class="controls">
					<input type="text" id="startDate" value="${leave.stringStartDate}" class="datepicker input-small" data-date-format="yyyy-mm-dd" />
					<input type="text" id="startTime" value="${leave.stringStartTime}" class="time input-small" />
				</div>
			</div>
			<div class="control-group">
				<label for="plainPassword" class="control-label">结束时间:</label>
				<div class="controls">
					<input type="text" id="endDate" value="${leave.stringEndDate}" class="datepicker input-small" data-date-format="yyyy-mm-dd" />
					<input type="text" id="endTime" value="${leave.stringEndTime}" class="time input-small" />
				</div>
			</div>
			<div class="control-group">
				<label for="groupList" class="control-label">请假原因:</label>
				<div class="controls">
					<textarea name="reason">${leave.reason}</textarea>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="reApply">是否继续申请：</label>
				<div class="controls">
					<select id="reApply" name="p_B_reApply">
						<option value="true">重新申请</option>
						<option value="false">结束流程</option>
					</select>
				</div>
			</div>
			<div class="form-actions">
				<button type="submit" class="btn"><i class="icon-ok"></i>完成任务</button>
			</div>
		</fieldset>
	</form>
</body>
</html>

chapter8-mail/src/main/webapp/WEB-INF/views/chapter7/leave/task-reportBack.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
	<link rel="stylesheet" href="${ctx}/js/common/plugins/timepicker.css">
	<title>请假申请--${task.name}</title>
	<script type="text/javascript" src="${ctx }/js/common/jquery.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap.min.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap-datepicker.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/plugins/bootstrap-timepicker.js"></script>
	<script type="text/javascript">
	$(function() {
		$('.datepicker').datepicker();
		$('.time').timepicker({
			minuteStep: 10,
            showMeridian: false
		});
	});

	function beforeSend() {
		$('input[name=p_DT_realityStartTime]').val($('#realityStartDate').val() + ' ' + $('#realityStartTime').val());
		$('input[name=p_DT_realityEndTime]').val($('#realityEndDate').val() + ' ' + $('#realityEndTime').val());
	}
	</script>
</head>
<body>
	<form action="${ctx }/chapter7/leave/task/complete/${task.id}" class="form-horizontal" method="post" onsubmit="beforeSend()">
		<input type="hidden" name="id" value="${leave.id}" />
		<input type="hidden" name="p_DT_realityStartTime" />
		<input type="hidden" name="p_DT_realityEndTime" />
		<fieldset>
			<legend><small>${task.name}</small></legend>
			<div class="control-group">
				<label for="loginName" class="control-label">申请人:</label>
				<div class="controls">${leave.userId}</div>
			</div>
			<div class="control-group">
				<label for="loginName" class="control-label">申请时间:</label>
				<div class="controls">${leave.applyTime}</div>
			</div>
			<div class="control-group">
				<label for="loginName" class="control-label">请假类型:</label>
				<div class="controls">${leave.leaveType}</div>
			</div>
			<div class="control-group">
				<label for="name" class="control-label">开始时间:</label>
				<div class="controls">${leave.startTime}</div>
			</div>
			<div class="control-group">
				<label for="plainPassword" class="control-label">结束时间:</label>
				<div class="controls">${leave.endTime}</div>
			</div>
			<div class="control-group">
				<label for="groupList" class="control-label">请假原因:</label>
				<div class="controls">${leave.reason}</div>
			</div>
			<div class="control-group">
				<label for="name" class="control-label">实际开始时间:</label>
				<div class="controls">
					<input type="text" id="realityStartDate" value="${leave.stringStartDate}" class="datepicker input-small" data-date-format="yyyy-mm-dd" />
					<input type="text" id="realityStartTime" value="${leave.stringStartTime}" class="time input-small" />
				</div>
			</div>
			<div class="control-group">
				<label for="plainPassword" class="control-label">实际结束时间:</label>
				<div class="controls">
					<input type="text" id="realityEndDate" value="${leave.stringEndDate}" class="datepicker input-small" data-date-format="yyyy-mm-dd" />
					<input type="text" id="realityEndTime" value="${leave.stringEndTime}" class="time input-small" />
				</div>
			</div>
			<div class="form-actions">
				<button type="submit" class="btn"><i class="icon-ok"></i>完成任务</button>
			</div>
		</fieldset>
	</form>
</body>
</html>