chapter12-task-attachment/src/main/java/me/kafeitu/activiti/chapter6/form/JavascriptFormType.java
package me.kafeitu.activiti.chapter6.form;

import org.activiti.engine.form.AbstractFormType;

/**
 * Javascript表单字段
 *
 * @author henryyan
 */
public class JavascriptFormType extends AbstractFormType {

    @Override
    public String getName() {
        return "javascript";
    }

    @Override
    public Object convertFormValueToModelValue(String propertyValue) {
        return propertyValue;
    }

    @Override
    public String convertModelValueToFormValue(Object modelValue) {
        return (String) modelValue;
    }
}

chapter12-task-attachment/src/main/java/me/kafeitu/activiti/chapter6/form/MyFormEngine.java
package me.kafeitu.activiti.chapter6.form;

import org.activiti.engine.form.StartFormData;
import org.activiti.engine.form.TaskFormData;
import org.activiti.engine.impl.form.FormEngine;

/**
 * 自定义表单引擎
 *
 * @author henryyan
 */
public class MyFormEngine implements FormEngine {

    @Override
    public String getName() {
        return "myformengine";
    }

    @Override
    public Object renderStartForm(StartFormData startForm) {
        javax.swing.JButton jButton = new javax.swing.JButton();
        jButton.setName("My Start Form Button");
        return jButton;
    }

    @Override
    public Object renderTaskForm(TaskFormData taskForm) {
        javax.swing.JButton jButton = new javax.swing.JButton();
        jButton.setName("My Task Form Button");
        return jButton;
    }

}

chapter12-task-attachment/src/main/java/me/kafeitu/activiti/web/chapter6/ProcessDefinitionController.java
package me.kafeitu.activiti.web.chapter6;

import me.kafeitu.activiti.chapter6.util.UserUtil;
import org.activiti.engine.FormService;
import org.activiti.engine.IdentityService;
import org.activiti.engine.RepositoryService;
import org.activiti.engine.form.FormProperty;
import org.activiti.engine.form.StartFormData;
import org.activiti.engine.identity.User;
import org.activiti.engine.repository.ProcessDefinition;
import org.activiti.engine.runtime.ProcessInstance;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

/**
 * 流程定义相关功能：读取动态表单字段、读取外置表单内容
 *
 * @author henryyan
 */
@Controller
@RequestMapping(value = "/chapter6")
public class ProcessDefinitionController {

    private Logger logger = LoggerFactory.getLogger(getClass());

    @Autowired
    RepositoryService repositoryService;

    @Autowired
    FormService formService;

    @Autowired
    IdentityService identityService;

    /**
     * 读取启动流程的表单字段
     */
    @RequestMapping(value = "getform/start/{processDefinitionId}")
    public ModelAndView readStartForm(@PathVariable("processDefinitionId") String processDefinitionId) throws Exception {
        ProcessDefinition processDefinition = repositoryService.createProcessDefinitionQuery().processDefinitionId(processDefinitionId).singleResult();
        boolean hasStartFormKey = processDefinition.hasStartFormKey();

        // 根据是否有formkey属性判断使用哪个展示层
        String viewName = "chapter6/start-process-form";
        ModelAndView mav = new ModelAndView(viewName);

        // 判断是否有formkey属性
        if (hasStartFormKey) {
            Object renderedStartForm = formService.getRenderedStartForm(processDefinitionId);
            mav.addObject("startFormData", renderedStartForm);
            mav.addObject("processDefinition", processDefinition);
        } else { // 动态表单字段
            StartFormData startFormData = formService.getStartFormData(processDefinitionId);
            mav.addObject("startFormData", startFormData);
        }
        mav.addObject("hasStartFormKey", hasStartFormKey);
        mav.addObject("processDefinitionId", processDefinitionId);
        return mav;
    }

    @SuppressWarnings("unchecked")
    @RequestMapping(value = "process-instance/start/{processDefinitionId}")
    public String startProcessInstance(@PathVariable("processDefinitionId") String pdid, HttpServletRequest request, RedirectAttributes redirectAttributes) {

        ProcessDefinition processDefinition = repositoryService.createProcessDefinitionQuery().processDefinitionId(pdid).singleResult();
        boolean hasStartFormKey = processDefinition.hasStartFormKey();

        Map<String, String> formValues = new HashMap<String, String>();

        if (hasStartFormKey) { // formkey表单
            Map<String, String[]> parameterMap = request.getParameterMap();
            Set<Entry<String, String[]>> entrySet = parameterMap.entrySet();
            for (Entry<String, String[]> entry : entrySet) {
                String key = entry.getKey();
                formValues.put(key, entry.getValue()[0]);
            }
        } else { // 动态表单
            // 先读取表单字段在根据表单字段的ID读取请求参数值
            StartFormData formData = formService.getStartFormData(pdid);

            // 从请求中获取表单字段的值
            List<FormProperty> formProperties = formData.getFormProperties();
            for (FormProperty formProperty : formProperties) {
                String value = request.getParameter(formProperty.getId());
                formValues.put(formProperty.getId(), value);
            }
        }

        // 获取当前登录的用户
        User user = UserUtil.getUserFromSession(request.getSession());
        // 用户未登录不能操作，实际应用使用权限框架实现，例如Spring Security、Shiro等
        if (user == null || StringUtils.isBlank(user.getId())) {
            return "redirect:/login?timeout=true";
        }
        identityService.setAuthenticatedUserId(user.getId());

        // 提交表单字段并启动一个新的流程实例
        ProcessInstance processInstance = formService.submitStartFormData(pdid, formValues);
        logger.debug("start a processinstance: {}", processInstance);
        redirectAttributes.addFlashAttribute("message", "流程已启动，实例ID：" + processInstance.getId());
        return "redirect:/chapter5/process-list";
    }

}

chapter12-task-attachment/src/main/java/me/kafeitu/activiti/web/chapter6/TaskController.java
package me.kafeitu.activiti.web.chapter6;

import me.kafeitu.activiti.chapter6.util.UserUtil;
import org.activiti.engine.FormService;
import org.activiti.engine.HistoryService;
import org.activiti.engine.IdentityService;
import org.activiti.engine.TaskService;
import org.activiti.engine.form.FormProperty;
import org.activiti.engine.form.TaskFormData;
import org.activiti.engine.history.HistoricTaskInstance;
import org.activiti.engine.identity.Group;
import org.activiti.engine.identity.User;
import org.activiti.engine.task.*;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Map.Entry;

/**
 * 任务控制器
 *
 * @author henryyan
 */
@Controller
@RequestMapping(value = "/chapter6")
public class TaskController {

    private static String TASK_LIST = "redirect:/chapter6/task/list";

    @Autowired
    TaskService taskService;

    @Autowired
    FormService formService;

    @Autowired
    IdentityService identityService;

    @Autowired
    HistoryService historyService;

    /**
     * 读取启动流程的表单字段
     */
    @RequestMapping(value = "task/list")
    public ModelAndView todoTasks(HttpSession session) throws Exception {
        String viewName = "chapter6/task-list";
        ModelAndView mav = new ModelAndView(viewName);
        User user = UserUtil.getUserFromSession(session);

        /*// 读取直接分配给当前人或者已经签收的任务
        List<Task> doingTasks = taskService.createTaskQuery().taskAssignee(user.getId()).list();

        // 等待签收的任务--废弃，用taskInvolvedUser代替
        // List<Task> waitingClaimTasks =
        // taskService.createTaskQuery().taskCandidateUser(user.getId()).list();

        // 受邀任务
        List<Task> involvedTasks = taskService.createTaskQuery().taskInvolvedUser(user.getId()).list();

        // 合并两种任务
        List<Task> allTasks = new ArrayList<Task>();
        allTasks.addAll(doingTasks);
        // allTasks.addAll(waitingClaimTasks);
        allTasks.addAll(involvedTasks);*/

        // 5.16版本可以使用一下代码待办查询
        List<Task> allTasks = taskService.createTaskQuery().taskCandidateOrAssigned(user.getId()).list();

        mav.addObject("tasks", allTasks);
        return mav;
    }

    /**
     * 签收任务
     */
    @RequestMapping(value = "task/claim/{id}")
    public String claim(@PathVariable("id") String taskId, @RequestParam(value = "nextDo", required = false) String nextDo, HttpSession session,
                        RedirectAttributes redirectAttributes) {
        String userId = UserUtil.getUserFromSession(session).getId();
        taskService.claim(taskId, userId);
        redirectAttributes.addFlashAttribute("message", "任务已签收");
        if (StringUtils.equals(nextDo, "handle")) {
            return "redirect:/chapter6/task/getform/" + taskId;
        } else {
            return TASK_LIST;
        }
    }

    /**
     * 反签收任务
     */
    @RequestMapping(value = "task/unclaim/{id}")
    public String unclaim(@PathVariable("id") String taskId, HttpSession session, RedirectAttributes redirectAttributes) {
        // 反签收条件过滤
        List<IdentityLink> links = taskService.getIdentityLinksForTask(taskId);
        for (IdentityLink identityLink : links) {
            // 如果一个任务有相关的候选人、组就可以反签收
            if (StringUtils.equals(IdentityLinkType.CANDIDATE, identityLink.getType())) {
                taskService.claim(taskId, null);
                redirectAttributes.addFlashAttribute("message", "任务已反签收");
                return TASK_LIST;
            }
        }
        redirectAttributes.addFlashAttribute("error", "该任务不允许反签收！");
        return TASK_LIST;
    }

    /**
     * 读取用户任务的表单字段
     */
    @RequestMapping(value = "task/getform/{taskId}")
    public ModelAndView readTaskForm(@PathVariable("taskId") String taskId) throws Exception {
        String viewName = "chapter6/task-form";
        ModelAndView mav = new ModelAndView(viewName);
        TaskFormData taskFormData = formService.getTaskFormData(taskId);
        Task task = null;

        // 外置表单
        if (taskFormData != null && taskFormData.getFormKey() != null) {
            Object renderedTaskForm = formService.getRenderedTaskForm(taskId);
            task = taskService.createTaskQuery().taskId(taskId).singleResult();
            mav.addObject("taskFormData", renderedTaskForm);
            mav.addObject("hasFormKey", true);
        } else if (taskFormData != null) { // 动态表单
            mav.addObject("taskFormData", taskFormData);
            task = taskFormData.getTask();
        } else { // 手动创建的任务（包括子任务）
            task = taskService.createTaskQuery().taskId(taskId).singleResult();
            mav.addObject("manualTask", true);
        }
        mav.addObject("task", task);

        // 读取任务参与人列表
        List<IdentityLink> identityLinksForTask = taskService.getIdentityLinksForTask(taskId);
        mav.addObject("identityLinksForTask", identityLinksForTask);

        // 读取所有人员
        List<User> users = identityService.createUserQuery().list();
        mav.addObject("users", users);

        // 读取所有组
        List<Group> groups = identityService.createGroupQuery().list();
        mav.addObject("groups", groups);

        // 读取子任务
        List<HistoricTaskInstance> subTasks = historyService.createHistoricTaskInstanceQuery().taskParentTaskId(taskId).list();
        mav.addObject("subTasks", subTasks);

        // 读取上级任务
        if (task != null && task.getParentTaskId() != null) {
            HistoricTaskInstance parentTask = historyService.createHistoricTaskInstanceQuery().taskId(task.getParentTaskId()).singleResult();
            mav.addObject("parentTask", parentTask);
        }

        // 读取附件
        List<Attachment> attachments = null;
        if (task.getTaskDefinitionKey() != null) {
            attachments = taskService.getTaskAttachments(taskId);
        } else {
            attachments = taskService.getProcessInstanceAttachments(task.getProcessInstanceId());
        }
        mav.addObject("attachments", attachments);

        return mav;
    }

    /**
     * 查看已结束任务
     */
    @RequestMapping(value = "task/archived/{taskId}")
    public ModelAndView viewHistoryTask(@PathVariable("taskId") String taskId) throws Exception {
        String viewName = "chapter6/task-form-archived";
        ModelAndView mav = new ModelAndView(viewName);
        HistoricTaskInstance task = historyService.createHistoricTaskInstanceQuery().taskId(taskId).singleResult();
        if (task.getParentTaskId() != null) {
            HistoricTaskInstance parentTask = historyService.createHistoricTaskInstanceQuery().taskId(task.getParentTaskId()).singleResult();
            mav.addObject("parentTask", parentTask);
        }
        mav.addObject("task", task);

        // 读取子任务
        List<HistoricTaskInstance> subTasks = historyService.createHistoricTaskInstanceQuery().taskParentTaskId(taskId).list();
        mav.addObject("subTasks", subTasks);

        // 读取附件
        List<Attachment> attachments = null;
        if (task.getTaskDefinitionKey() != null) {
            attachments = taskService.getTaskAttachments(taskId);
        } else {
            attachments = taskService.getProcessInstanceAttachments(task.getProcessInstanceId());
        }
        mav.addObject("attachments", attachments);

        return mav;
    }

    /**
     * 读取启动流程的表单字段
     */
    @SuppressWarnings("unchecked")
    @RequestMapping(value = "task/complete/{taskId}")
    public String completeTask(@PathVariable("taskId") String taskId, HttpServletRequest request, RedirectAttributes redirectAttributes) throws Exception {

        // 设置当前操作人，对于调用活动可以获取到当前操作人
        String currentUserId = UserUtil.getUserFromSession(request.getSession()).getId();
        identityService.setAuthenticatedUserId(currentUserId);

        Task task = taskService.createTaskQuery().taskId(taskId).singleResult();
        // 如果任务的流程定义任务Key为空则认为是手动创建的任务
        if (StringUtils.isBlank(task.getTaskDefinitionKey())) {
            taskService.complete(taskId);
            return TASK_LIST;
        }

        // 权限检查-任务的办理人和当前人不一致不能完成任务
        if (!task.getAssignee().equals(currentUserId)) {
            redirectAttributes.addFlashAttribute("error", "没有权限，不能完成该任务！");
            return "redirect:/chapter6/task/getform/" + taskId;
        }

        // 单独处理被委派的任务
        if (task.getDelegationState() == DelegationState.PENDING) {
            taskService.resolveTask(taskId);
            return TASK_LIST;
        }

        TaskFormData taskFormData = formService.getTaskFormData(taskId);
        String formKey = taskFormData.getFormKey();
        // 从请求中获取表单字段的值
        List<FormProperty> formProperties = taskFormData.getFormProperties();
        Map<String, String> formValues = new HashMap<String, String>();

        if (StringUtils.isNotBlank(formKey)) { // formkey表单
            Map<String, String[]> parameterMap = request.getParameterMap();
            Set<Entry<String, String[]>> entrySet = parameterMap.entrySet();
            for (Entry<String, String[]> entry : entrySet) {
                String key = entry.getKey();
                formValues.put(key, entry.getValue()[0]);
            }
        } else { // 动态表单
            for (FormProperty formProperty : formProperties) {
                if (formProperty.isWritable()) {
                    String value = request.getParameter(formProperty.getId());
                    formValues.put(formProperty.getId(), value);

chapter12-task-attachment/src/main/webapp/WEB-INF/views/chapter6/start-process-form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="org.activiti.engine.form.*, org.apache.commons.lang3.*" %>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
	<title>启动流程</title>
	<script type="text/javascript" src="${ctx }/js/common/jquery.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap.min.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap-datepicker.js"></script>
	<script type="text/javascript">
	$(function() {
		$('.datepicker').datepicker();

		// 选择人对话框
		$('#userModal').on('show', function() {
			$('#userModal select').html('');
			$.getJSON(ctx + '/user/list', function(datas) {
				$.each(datas, function(k, v) {
					var $opg = $('<optgroup/>', {
						label: k
					}).appendTo('#userModal select');
					$.each(v, function() {
						$('<option/>', {
							'value': this.id,
							'text': this.firstName + ' ' + this.lastName + '（' + this.id + '）'
						}).appendTo($opg);
					});
				});
			});
		});

		// 单击打开选择人对话框
		$('.users').live('click', function() {
			$('body').data('usersEle', this);
			$('#userModal').modal('show');
		});

		$('#userModal .ok').click(function() {
			var ele = $('body').data('usersEle');
			var users = new Array();
			$('#userModal select option:selected').each(function() {
				users.push($(this).val());
			});
			$(ele).val(users);
			$('#userModal').modal('hide');
		});
	});
	</script>
</head>
<body>
	<h3>启动流程—
		<c:if test="${hasStartFormKey}">
			[${processDefinition.name}]，版本号：${processDefinition.version}
		</c:if>
		<c:if test="${!hasStartFormKey}">
			[${startFormData.processDefinition.name}]，版本号：${startFormData.processDefinition.version}
		</c:if>
	</h3>
	<hr/>
	<form action="${ctx }/chapter6/process-instance/start/${processDefinitionId}" class="form-horizontal" method="post">
		<c:if test="${hasStartFormKey}">
		${startFormData}
		</c:if>

		<c:if test="${!hasStartFormKey}">
			<c:forEach items="${startFormData.formProperties}" var="fp">
				<c:set var="fpo" value="${fp}"/>
				<c:set var="required" value="${fp.required ? 'required' : ''}" />
				<%
					// 把需要获取的属性读取并设置到pageContext域
					FormType type = ((FormProperty)pageContext.getAttribute("fpo")).getType();
					String[] keys = {"datePattern"};
					for (String key: keys) {
						pageContext.setAttribute(key, ObjectUtils.toString(type.getInformation(key)));
					}
				%>
				<div class="control-group">
				<%-- 文本或者数字类型 --%>
				<c:if test="${fp.type.name == 'string' || fp.type.name == 'double' || fp.type.name == 'long'}">
					<label class="control-label" for="${fp.id}">${fp.name}:</label>
					<div class="controls">
						<input type="text" id="${fp.id}" name="${fp.id}" data-type="${fp.type.name}" ${required}/>
					</div>
				</c:if>

				<%-- 大文本 --%>
				<c:if test="${fp.type.name == 'bigtext'}">
					<label class="control-label" for="${fp.id}">${fp.name}:</label>
					<div class="controls">
						<textarea id="${fp.id}" name="${fp.id}" data-type="${fp.type.name}" ${required}></textarea>
					</div>
				</c:if>

				<%-- 日期 --%>
				<c:if test="${fp.type.name == 'date'}">
					<label class="control-label" for="${fp.id}">${fp.name}:</label>
					<div class="controls">
						<input type="text" id="${fp.id}" name="${fp.id}" class="datepicker" data-type="${fp.type.name}" data-date-format="${fn:toLowerCase(datePattern)}" ${required} />
					</div>
				</c:if>

				<%-- Javascript --%>
				<c:if test="${fp.type.name == 'javascript'}">
					<script type="text/javascript">${fp.value};</script>
				</c:if>

				<%-- 选择人员 --%>
				<c:if test="${fp.type.name == 'users'}">
					<label class="control-label" for="${fp.id}">${fp.name}:</label>
					<div class="controls">
						<input type="text" id="${fp.id}" name="${fp.id}" data-type="${fp.type.name}" class="users"readonly />
					</div>
				</c:if>
				</div>
			</c:forEach>
		</c:if>

		<%-- 按钮区域 --%>
		<div class="control-group">
			<div class="controls">
				<a href="javascript:history.back();" class="btn"><i class="icon-backward"></i>返回列表</a>
				<button type="submit" class="btn"><i class="icon-play"></i>启动流程</button>
			</div>
		</div>
	</form>

	<div id="userModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="userModalLabel" aria-hidden="true" style="width: 260px;">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="userModalLabel">选择人员</h3>
	  </div>
	  <div class="modal-body">
	  	<select multiple="multiple" style="height: 200px;"></select>
	  </div>
	  <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	    <button class="btn btn-primary ok">确定</button>
	  </div>
	</div>
</body>
</html>

chapter12-task-attachment/src/main/webapp/WEB-INF/views/chapter6/task-form-archived.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="org.activiti.engine.form.*, org.apache.commons.lang3.*" %>
<!DOCTYPE html>
<html>
<head>
	<%@ include file="/common/global.jsp"%>
	<%@ include file="/common/meta.jsp" %>
	<%@ include file="/common/include-base-styles.jsp" %>
	<title>已归档任务办理</title>
	<style type="text/css">
	.task-infos {margin-left: 20px;}
	.task-infos span {margin-right: 20px;}
	#commentList span {padding: 0 5px 0 5px;}
	#commentList ol {margin-left: 3em;}
	</style>

	<script type="text/javascript" src="${ctx }/js/common/jquery.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap.min.js"></script>
	<script type="text/javascript" src="${ctx }/js/common/bootstrap-datepicker.js"></script>
	<script type="text/javascript">
		var taskId = '${task.id}';
		var processInstanceId = '${task.processInstanceId}';
	</script>
	<script type="text/javascript" src="${ctx }/js/modules/chapter12/events.js"></script>
	<script type="text/javascript">
	$(function() {
		$('.attachment-item').tooltip();
		// 读取事件列表
		readComments();
	});
	</script>
</head>
<body>
	<h3>任务—[${task.name}]
		<c:if test="${not empty task.processDefinitionId}">
			，流程定义ID：[${task.processDefinitionId}]
		</c:if>
	</h3>
	<!-- 任务属性 -->
	<p class="task-infos text-left">
		<span><i class="icon-calendar"></i>到期日：
			<span class='due-date'>
				<c:if test="${empty task.dueDate}">无到期日</c:if>
				<c:if test="${not empty task.dueDate}">
					<fmt:formatDate value="${task.dueDate}" pattern="yyyy-MM-dd"/>
				</c:if>
			</span>
		</span>
		<span><i class="icon-flag"></i>优先级：
			<span class='priority'>
				<c:if test="${empty task.priority}">无到期日</c:if>
				<c:if test="${not empty task.priority}">
					<c:if test="${task.priority == 0}">低</c:if>
					<c:if test="${task.priority == 50}">中</c:if>
					<c:if test="${task.priority == 100}">高</c:if>
				</c:if>
			</span>
		</span>
		<span><i class="icon-calendar"></i>创建日期：
			<fmt:formatDate value="${task.startTime}" pattern="yyyy-MM-dd hh:mm:ss"/>
		</span>
		<span><i class="icon-calendar"></i>完成日期：
			<fmt:formatDate value="${task.endTime}" pattern="yyyy-MM-dd hh:mm:ss"/>
		</span>
		<c:if test="${not empty parentTask}">
			<hr/>
			<%-- 运行中任务 --%>
			<c:if test="${empty parentTask.endTime}">
				<div>
					该任务属于：<a href="${ctx}/chapter6/task/getform/${parentTask.id}">${parentTask.name}</a>
				</div>
			</c:if>

			<%-- 已结束任务 --%>
			<c:if test="${not empty parentTask.endTime}">
				<div>
					该任务属于：<a href="${ctx}/chapter6/task/archived/${parentTask.id}">${parentTask.name}</a>
				</div>
			</c:if>
		</c:if>
	</p>
	<hr/>
	<%-- 任务描述 --%>
	<c:if test="${empty task.description}">
		<p class="text-muted">该任务无描述。</p>
	</c:if>
	<c:if test="${not empty task.description}">
		<p class="text-infos">${task.description}</p>
	</c:if>

	<hr/>
	<p class="task-infos text-left">
		<h4 style="display:inline;">任务人员</h4>
		<div class="row">
			<div class="span4">
				<span><i class="icon-user"></i>拥有人：<span id="owner">${empty task.owner ? '无' : task.owner}</span></span>
			</div>
			<div class="span4">
				<span><i class="icon-user"></i>办理人：<span id="assignee">${empty task.assignee ? '无' : task.assignee}</span></span>
			</div>
		</div>
	</p>
	<hr/>

	<!-- 子任务 -->
	<p class="text-left">
		<h4 style="display:inline;">子任务</h4>
		<ul class="unstyled">
			<c:forEach items="${subTasks}" var="subTask">
			<li>
				<%-- 根据任务完成状态显示不同的图标 --%>
				<i class="icon-${empty subTask.endTime ? 'tasks' : 'ok'}"></i>

				<c:if test="${empty subTask.endTime}">
					<a href="${ctx}/chapter6/task/getform/${subTask.id}" class="task-name">${subTask.name}</a>
				</c:if>

				<c:if test="${not empty subTask.endTime}">
					<a href="${ctx}/chapter6/task/archived/${subTask.id}" class="task-name">
					${subTask.name}（完成时间：<fmt:formatDate value="${subTask.endTime}" pattern="yyyy-MM-dd hh:mm:ss"/>）</a>
				</c:if>
			</li>
		</c:forEach>
		</ul>
	</p>
	<hr/>

	<!-- 附件 -->
	<div>
		<h4 style="display:inline;">相关附件</h4>
		<ul class="unstyled">
			<c:forEach items="${attachments}" var="attachment">
			<li>
				<%-- url类型的文件 --%>
				<c:if test="${attachment.type == 'url'}">
					<a href="${attachment.url}" target="_blank" data-toggle="tooltip" title="地址：${attachment.url}<br/>描述：${attachment.description}" data-placement="right" class="attachment-item"><i class="icon-share"></i>${attachment.name}</a>
				</c:if>

				<%-- 文件类型的文件 --%>
				<c:if test="${attachment.type != 'url'}">
					<a href="${ctx}/chapter12/attachment/download/${attachment.id}" target="_blank" data-toggle="tooltip" title="${attachment.description}" data-placement="right" class="attachment-item"><i class="icon-file"></i>${attachment.name}</a>
				</c:if>
			</li>
		</c:forEach>
		</ul>
	</div>
	<hr/>
	<%-- 事件区域，参考events.js --%>
	<fieldset id="commentList">
		<legend>事件列表</legend>
		<%-- 列表是通过js发送ajax请求后动态生成的 --%>
		<ol></ol>
	</fieldset>
</body>
</html>